name: server-tests-workflows

on: push

jobs:
  test-backend:
    runs-on: macos-latest
    container: node:lts-alpine

    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto backend and run tests
        run: cd backend && npm i && npm test