name: server-tests-workflows

on: push

jobs:
  test-server:
    runs-on: unbuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Goto backend and run tests
        run: cd backend && npm i && npm test